wood: 
  display: Wood
  qty : 10
  img: Tiles/sm_tree.gif
spear: 
  display: Spears
  qty: 10
  img: Spear/sm_spear.gif
fish: 
  display: Fish
  qty: 4
  img: Fish/sm_fish.gif
rock: 
  display: Rock
  qty: 20
  img: Tiles/sm_rock.gif
brick:
  display: Bricks
  qty: 0
  img: Items/sm_brick.gif
wall:
  display: Wall
  qty: 3
  img: Items/sm_wall.gif