health:
  display: Health
  qty : 100
  full: green
  empty: red
  tick: 1
  ticks: True
  label: black
energy:
  display: Energy
  qty : 100
  full: green
  empty: red
  tick: -0.5
  ticks: True
  label: black
thirst:
  display: Thirst
  qty : 100
  full: green
  empty: red
  tick: -0.5
  ticks: True
  label: black
hunger:
  display: Hunger
  qty : 100
  full: green
  empty: red
  tick: -0.5
  ticks: True
  label: black

